### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by will** [crystal-lang/heroku-buildpack-crystal#2]
It looks like this is installing Crystal 0.5.3 [eac061b](Thu Nov 6 21:29:19 UTC 2014)

**Comment by will** [comment]
Also the existing url is not over https

**Comment by will** [comment]
@waj @asterite I'd like to write up a post on using crystal on heroku, but I'd like the buildpack working properly first.

**Comment by zamith** [comment]
@will You can use [my fork](https://github.com/zamith/heroku-buildpack-crystal), which is updated with the latest version. If you have any issue don't hesitate in opening an issue there.
