### ISSUE TITLE
Unable to build Crystal 0.33

### ISSUE THREAD

**Issue by ejstembler** [crystal-lang/heroku-buildpack-crystal#38]
I have a Crystal 0.33 app on Heroku, it's worked for a while flawlessly.  However, I recently tried to push a minor change and the build broke since it installed version 0.35.1 which is incompatible with my 0.33 code.  Heroku support pointed out that I needed a `.crystal-version` file.  So, I created one with `0.33` in it.  I'm getting this error now:

```console
remote: -----> Installing Crystal (0.33 due to .crystal-version file) from ... curl: no URL specified!
remote: curl: try 'curl --help' or 'curl --manual' for more information
remote: 
remote: gzip: stdin: unexpected end of file
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote:  !     Push rejected, failed to compile Crystal app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to xxxxx.
```

So, is there a way to specify the URL with the version?  How can I fix this?

Thanks!

**Comment by jhass** [comment]
Please try an explicit version, so `0.33.0`.

**Comment by ejstembler** [comment]
@jhass Ah, that worked! Thanks!

I noticed my `shard.yml` file has `crystal: 0.33` in it.  Should I change that to `crystal: 0.33.0` as well?

**Comment by jhass** [comment]
Yes, sounds reasonable. A future version of the buildpack is likely to read that property if no `.crystal-version` file is present.
