### ISSUE TITLE
Port config from ENV

### ISSUE THREAD

**Issue by arr-dev** [crystal-lang/heroku-buildpack-crystal#6]
Not experienced with crystal, 
but why not set port from ENV, 
like other buildpacks do (ruby,go)?

**Comment by zamith** [comment]
The port should be coming from ENV, I believe. Is it not working for you?

**Comment by bcardiff** [comment]
@arr-dev  you can set the port in your program as

``` crystal
port = ENV["PORT"]?.try(&.to_i) || 8080
```

And it will work in heroku but then, instead of using a command line option you will need to set the environment variable. Totally viable, but I like more the command line option alternative.

**Comment by zamith** [comment]
@arr-dev Does that answer your question? Can we close this?

**Comment by arr-dev** [comment]
That wasn't clear by looking at the docs, but yes, sure, can be closed.

**Comment by zamith** [comment]
@bcardiff Maybe we can add something on the README in this regard. What do you think?

**Comment by bcardiff** [comment]
@zamith Yeap, I agree. A short section with port/binding description options and read more in the post it should be enough. Otherwise the people that reach this repo has no clue how to use it.

**Comment by zamith** [comment]
@arr-dev Do you want to take a stab at it?

**Comment by arr-dev** [comment]
@zamith Sure, I'll give it a go.

**Comment by zamith** [comment]
Awesome. Thanks a lot.

**Comment by arr-dev** [comment]
Tried to formulate it in #7, but when I thought about it, 
I wanted to change linked blog post more than the README, 
since that was the actual cause of my confusion.

Can I ask what's the rationale in setting port from CLI instead of using `ENV["PORT"]`?
It seems much easier for apps to just read ENV.

**Comment by bcardiff** [comment]
1. I think it is more common to pass options in CLI than in ENV.
2. The `--port $PORT` [was already there](https://github.com/crystal-lang/heroku-buildpack-crystal/commit/f1c211a46a1b34ab94b3549a2c9a35a898937ebd) :-)
3. Rails and other programs that starts an http server use `--port`

I know that `crystal foo.cr -- --port 9090` might be confusing but usually the default port should be fine in development. When foo is compiled, `./foo --port 9090` looks better that `PORT=9090 ./foo` IMO.

This whole story might get simplified if a Procfile is supported/generated for dynos and the processes for each role will need to be declared.

**Comment by arr-dev** [comment]
Thanks for the elaborate response :-)
Cheers
